 login: &login
   adapter: mysql2
   host: localhost
   host: 127.0.0.1
   encoding: utf8

 development:
   database: snowmoon_inlinedev
   username: snowmoon_inlined
   password: inln16ed
   <<: *login

 test:
   database: inline_test
   username: root
   password: t9ohqa
   <<: *login

 production:
   database: glass_inlineproduction
   username: glass_inline
   password: inline
   <<: *login
